"""Innovation 5: Unsupervised Novelty & Out-of-Distribution Pattern Detector.

Source Authority & Method:
- Detects unusual, out-of-distribution telemetry behavior relative to learned historical normal fleet patterns.
- Uses an unsupervised Isolation Forest fitted strictly on historical pre-decision feature matrices (Zero Lookahead).
- Does NOT equate novelty with physical failure ("Novel != Definitely Faulty").
- Outputs a continuous Novelty Score in [0.0, 1.0], anomaly indicator, and primary feature divergence drivers.
"""

from __future__ import annotations

import logging
from typing import Any
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

logger = logging.getLogger(__name__)


class FleetNoveltyDetector:
    """Unsupervised fleet novelty and out-of-distribution anomaly detector."""

    def __init__(
        self,
        n_estimators: int = 100,
        contamination: float = 0.05,
        random_state: int = 42,
    ) -> None:
        self.n_estimators = n_estimators
        self.contamination = contamination
        self.random_state = random_state
        self.scaler = StandardScaler()
        self.model = IsolationForest(
            n_estimators=self.n_estimators,
            contamination=self.contamination,
            random_state=self.random_state,
            n_jobs=-1,
        )
        self.feature_names_: list[str] = []
        self.is_fitted_: bool = False

    def fit(self, X: pd.DataFrame, feature_cols: list[str] | None = None) -> "FleetNoveltyDetector":
        """Fit unsupervised novelty detector on historical training features strictly prior to cutoff."""
        if feature_cols is not None:
            self.feature_names_ = feature_cols
            X_mat = X[feature_cols].fillna(0.0)
        else:
            self.feature_names_ = list(X.columns)
            X_mat = X.fillna(0.0)

        X_scaled = self.scaler.fit_transform(X_mat)
        self.model.fit(X_scaled)
        self.is_fitted_ = True
        return self

    def score_samples(self, X: pd.DataFrame) -> pd.DataFrame:
        """Compute novelty scores and driver attributes on candidate features.

        Args:
            X: DataFrame containing the features to evaluate.

        Returns:
            pd.DataFrame containing:
            - feat_novelty_score: float in [0.0, 1.0] (higher = more novel/anomalous)
            - is_novel_anomaly: int (1 if Isolation Forest flags as outlier, 0 otherwise)
            - novelty_primary_driver: str (feature with highest standardized deviation)
        """
        if not self.is_fitted_:
            raise RuntimeError("FleetNoveltyDetector must be fitted before scoring samples.")

        X_mat = X[self.feature_names_].fillna(0.0)
        X_scaled = self.scaler.transform(X_mat)

        # Isolation Forest decision_function: lower score = more abnormal
        raw_scores = self.model.decision_function(X_scaled)
        # Convert to [0.0, 1.0] where 1.0 = highest novelty
        # Typically raw_scores range from -0.3 to +0.3
        novelty_score = 1.0 / (1.0 + np.exp(8.0 * raw_scores))

        preds = self.model.predict(X_scaled)
        is_anomaly = (preds == -1).astype(int)

        # Identify primary diverging feature per row
        abs_devs = np.abs(X_scaled)
        top_driver_indices = np.argmax(abs_devs, axis=1)
        drivers = [self.feature_names_[idx] for idx in top_driver_indices]

        out_df = pd.DataFrame(index=X.index)
        if "gateway_id" in X.columns:
            out_df["gateway_id"] = X["gateway_id"]
        if "decision_week" in X.columns:
            out_df["decision_week"] = X["decision_week"]

        out_df["feat_novelty_score"] = np.clip(novelty_score, 0.0, 1.0).round(4)
        out_df["is_novel_anomaly"] = is_anomaly
        out_df["novelty_primary_driver"] = drivers

        return out_df


def get_novelty_feature_columns() -> list[str]:
    """Return the feature columns generated by the novelty detector."""
    return [
        "feat_novelty_score",
        "is_novel_anomaly",
    ]
